# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @name Gibbs 
NULL

#' @importFrom stats rbinom rbeta
NULL

gibbsSampler <- function(N, burn, a, b, n) {
    .Call('_SA23204198_gibbsSampler', PACKAGE = 'SA23204198', N, burn, a, b, n)
}

